import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { Button, ButtonGroup } from "@chakra-ui/react";

import { api } from "t3-poll/utils/api";

const Home: NextPage = () => {
  const { user, isSignedIn } = useUser();

  const { data, isLoading } = api.listings.getAll.useQuery();

  console.log("data", data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {isSignedIn ? <SignOutButton /> : <SignIn />}
        <Button variant="unstyled">Button</Button>
      </main>
    </>
  );
};

export default Home;
