import { SignIn, SignOutButton, useUser } from "@clerk/nextjs";
import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { user, isSignedIn } = useUser();

  console.log("user", user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {isSignedIn ? <SignOutButton /> : <SignIn />}
      </main>
    </>
  );
};

export default Home;
